name: zone_pilot
description: "AI-Powered Multi-App Assistant for Gig Drivers"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add this line for icons
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  google_maps_flutter: ^2.12.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  permission_handler: ^11.3.1
  app_settings: ^5.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  external_app_launcher: ^4.0.2
  image_picker: ^1.1.2
  firebase_storage: ^11.7.4
  geolocator: ^12.0.0
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/